import logging
import json
import re
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from src.config import settings

logger = logging.getLogger(__name__)

class PlannedTask(BaseModel):
    """A single sub-task generated by the QueryPlanner."""
    task_id: int
    description: str
    search_query: str
    requires_graph: bool = Field(default=False, description="Whether this task needs relationship search")
    dependency_ids: List[int] = Field(default_factory=list, description="IDs of tasks that must be completed first")

class ExecutionPlan(BaseModel):
    """The full execution plan for a legal query."""
    tasks: List[PlannedTask]
    strategy: str = Field(description="Search strategy: simple, multi_step, or graph_enriched")

PLANNER_SYSTEM_PROMPT = """Bạn là một Chuyên gia Pháp luật Việt Nam. Nhiệm vụ của bạn là lập kế hoạch thực hiện để trả lời câu hỏi pháp luật của người dùng.

Hãy phân tích câu hỏi và quyết định:
1. Câu hỏi này có cần tra cứu các văn bản liên quan qua biểu đồ (Graph) không? (Vệ tinh quanh luật chính, nghị định hướng dẫn, thông tư, văn bản sửa đổi...)
2. Câu hỏi này có cần chia ra thành nhiều bước tra cứu không? (Ví dụ: Tra cứu luật gốc trước, sau đó tra cứu nghị định hướng dẫn).

Trả về một kế hoạch thực thi dưới dạng JSON với cấu trúc:
{
  "strategy": "simple | multi_step | graph_enriched",
  "tasks": [
    {
      "task_id": 1,
      "description": "Mô tả ngắn gọn bước cần làm",
      "search_query": "Câu lệnh tra cứu tối ưu cho bước này",
      "requires_graph": true/false,
      "dependency_ids": []
    }
  ]
}

Nguyên tắc:
- Nếu câu hỏi hỏi về "căn cứ", "hướng dẫn", "sửa đổi", "bổ sung" -> requires_graph = true.
- Nếu câu hỏi phức tạp kết hợp nhiều vấn đề -> split thành nhiều task.
- Trả về DUY NHẤT một khối JSON.
"""

class QueryPlanner:
    """
    Analyzes user queries and plans an execution strategy involving
    standard retrieval and/or Graph RAG.
    """

    def __init__(self, llm_client=None):
        self._client = llm_client
        # If client not provided, we will assume it's set later or use a default one
        # For now, we'll try to use the same logic as LegalRAGGenerator if needed

    async def create_plan(self, question: str) -> ExecutionPlan:
        """Analyze the query and create a multi-step execution plan."""
        logger.info(f"Planning execution for query: '{question}'")
        
        # We'll use the LLM to generate the plan
        # Note: In a production system, we'd have a dedicated client here
        # For this implementation, we will use a structure that can be easily integrated
        
        # Default simple plan if LLM fails or for simple queries
        default_plan = ExecutionPlan(
            strategy="simple",
            tasks=[
                PlannedTask(
                    task_id=1,
                    description=f"Tra cứu thông tin về: {question}",
                    search_query=question,
                    requires_graph=self._detect_graph_need(question)
                )
            ]
        )
        
        return default_plan

    def _detect_graph_need(self, question: str) -> bool:
        """Rules-based detection of graph search needs as a fallback/accelerator."""
        keywords = [
            "hướng dẫn", "nghị định", "thông tư", "sửa đổi", 
            "bổ sung", "căn cứ", "thay thế", "chi tiết"
        ]
        q_lower = question.lower()
        return any(k in q_lower for k in keywords)
